version: '3.0'

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --generate-cohort-by-sql queries_rcloud.sql --database-url=postgres://postgres:1234@192.168.0.16:5432/rcloud
    # run: cohortextractor:latest generate_cohort --generate-cohort-by-sql queries_rcloud.sql
    outputs:
      highly_sensitive:
        cohort: output/input.csv
  train_model:
    run: python:latest python analysis/train_model.py
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        model: output/regression_model.joblib
  predict_model:
    run: python:latest python analysis/model_predict.py
    needs: [train_model]
    outputs:
      moderately_sensitive:
        stats: output/stats.txt
  r_test:
    run: r:latest Rscript analysis/test_r.R
    needs: [predict_model]
    outputs:
      moderately_sensitive:
        plot1: output/r_plot.png
        plot2: output/r_plot2.png
