version: '3.0'

expectations:
  population_size: 0

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --generate-cohort-by-sql queries_rcloud.sql --database-url=postgres://postgres:1234@192.168.0.16:5432/rcloud
    outputs:
      highly_sensitive:
        cohort: output/input.csv
