version: '3.0'

actions:

  generate_study_population:
    # run: cohortextractor:latest generate_cohort --generate-cohort-by-sql queries_rcloud.sql --database-url=postgres://postgres:1234@192.168.0.16:5432/rcloud
    run: cohortextractor:latest generate_cohort --generate-cohort-by-sql queries_rcloud.sql
    outputs:
      highly_sensitive:
        cohort: output/input.csv
  train_model:
    run: python:latest python analysis/train_model.py
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        cohort: output/regression_model.joblib
  predict_model:
    run: python:latest python analysis/model_predict.py
    needs: [train_model]
    outputs:
      moderately_sensitive:
        cohort: output/stats.txt
