version: '3.0'

expectations:
  population_size: 0

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --generate-cohort-by-sql queries.sql
    outputs:
      highly_sensitive:
        cohort: output/input.csv
