version: '3.0'

expectations:
  population_size: 0

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --database-url mssql://SA:Your_password123!@mssql:1433/Test_OpenCorona
    outputs:
      highly_sensitive:
        cohort: output/input.csv
